### PR TITLE
Pure CSS Pagination

### PR DESCRIPTION
**Pull request by Jakeii**
I was reading about CSS columns and it sparked an idea to use them for our ereader.

This is pretty slick, way less code, great performance, and splits the pages perfectly.

I know I mentioned abandoning pages alltogether, but i think this straghtens it all out, shall i continue with this? @jaylarson85 @usernamenumber 

Just needs a little more work to get feature parity with our current way of doing it.

TODO:
- [ ] Section and subsection links
- [x] Navigating to next section at the end of the current

### CODE REVIEW

**Comment by neerajkamdar** [comment]
Great idea to use CSS Columns Jake. Just tried it out and it's working quite well.

**Comment by usernamenumber** [comment]
We know Fred is fine with the page-based implementation, so I think we
would need to ask if we wanted to do the single-page thing, but this is
just a (hopefully) better implementation of what we've already agreed to
deliver, so I'd say no.

My only concern would be about how the CSS-based approach performs on older
devices. If we find that we have to have a hard cutoff for version X of the
mobile OS/browser, I think that's something we should be sure Fred et al
are on-board with.

--Brad

**Comment by Jakeii** [comment]
@usernamenumber it seems fairly well supported http://caniuse.com/#feat=multicolumn , but I thought we were only relying on browsers for the demo we did?

**Comment by usernamenumber** [comment]
Well yeah, but we're on the hook for an actual product by August.

In any case, this sounds like a great find to me. Yay for not re-inventing
wheels!

**Comment by Jakeii** [comment]
OK nearly there, much better way now, also all the sections are loaded at once, so navigating between is seamless.

**Comment by Jakeii** [comment]
@usernamenumber I had to make some modifications to the book content, namely adding some attributes to the subsection anchors, and adding anchors for sections.

**Comment by usernamenumber** [comment]
Are those changes committed into [funzo-cse](https://github.com/usernamenumber/funzo-cse/) (I see a commit from you, but it's ten days old, so I just want to check)? If not, could you please integrate it there so we know it won't get lost the next time we build a version of the book?

**Comment by Jakeii** [comment]
I'll wait till this is merged?

**Comment by Jakeii** [comment]
I think this is stable enough to merge? Changes to the content is in a PR https://github.com/usernamenumber/funzo-cse/pull/1

**Pull request merged**
